### PR TITLE
Changes to Exchanges

### PR DESCRIPTION
**Pull request by roast-nav**
Added simple swap, social send, stake cube, coin switch, and coinzark across en,es,it,jp,kr,ru,zh. Removed cryptopia.

### CODE REVIEW

**Comment by proletesseract** [comment]
Resolves issues: #194 #196 #189 #199 #200 #201

**Comment by proletesseract** [comment]
Preview Link: https://deploy-preview-205--navcoin.netlify.com/en/buy-navcoin

**Comment by roast-nav** [comment]
#205 Changes have been made.

**Comment by proletesseract** [comment]
@roast-nav can you paste your NAV address for bounty payment?

6 x bounty-low = 600 NAV.

The payment request for the bounty program hasn't been approved just yet. I will make the payment as soon as the funds are available. Probably about ~6 days from now.

**Comment by roast-nav** [comment]
NNcAFdrDtTdoTFWFQNL341guP3RoLXQ6G6

**Comment by proletesseract** [comment]
@roast-nav paid:

https://www.navexplorer.com/tx/6903cb7cc342aab139a18cf396ebd16e499f40e73741da3765364b5f437fcae0

**Pull request merged**
