### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by aguycalled**
### Description

Describe in detail what the pull request fixes, adds or removes.

### Issues Resolved

Please tag the issue numbers that this pull request resolves (eg #100, #101).

### Preview Links

Paste the preview links where the changes can be viewed on the netlify deploy preview (you'll need to add these after the PR is made and the preview is deployed).

eg.

https://deploy-preview-205--navcoin.netlify.com/en/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/es/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/it/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/jp/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/kr/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/ru/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/zh/buy-navcoin

The preview can be found on the pull reqeuest once it's made by clicking `show all checks` > `details`.

### Checklist

- [ ] Have you assigned/claimed the issues you've resolved in this pull request?
- [ ] Have the issues been moved to the QA column of the Navcoin Websites project? 
- [ ] Have you checked there are no merge conflicts?
- [ ] Have you tested the changes work across both mobile and desktop?

### CODE REVIEW

**Review by sakdeniz — APPROVED** [review]

**Comment by chasingkirkjufell** [comment]
the home page, can we make it larger? 
image

**Comment by chasingkirkjufell** [comment]
https://deploy-preview-322--navcoin.netlify.app/en/

**Comment by chasingkirkjufell** [comment]
at least same font size as the tabs i'd say 
image

**Review by chasingkirkjufell — CHANGES_REQUESTED** [review]
font size adjustments

**Review by sakdeniz — APPROVED** [review]

**Review by chasingkirkjufell — APPROVED** [review]

**Pull request merged**
