### PR TITLE
Updated contributors

### LINKED ISSUE #212: Update the list of contributors to navcoin-core
### Description
The list of contributors to NavCoin Core needs updating on the for-developers page.

https://navcoin.org/en/for-developers

should match this list -> https://github.com/navcoin/navcoin-core/graphs/contributors

### Motivation
Accurately reflect the efforts of new contributors to core.

### Acceptance Criteria

- [ ] List of contributors should match what is on the github contributors page.
- [ ] Should have image, github username, link to github profile for each.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or amended as necessary.

### PR DESCRIPTION
**Pull request by amescarda**
closes #212

### CODE REVIEW

**Comment by proletesseract** [comment]
approved and merged. @amescarda can you post your NAV address for bounty payment please?

**Comment by mxaddict** [comment]
@amescarda what is you NAV address?

**Comment by amescarda** [comment]
@mxaddict @proletesseract this is my NAV address: NarTqedb6aancvuqbtsGKXHcESG79v2WQW

**Comment by proletesseract** [comment]
@amescarda paid

https://www.navexplorer.com/tx/3612d2c4da122d75b72a6acb209bc81680f92b888fdf2da9954c10cfc535f859

**Pull request merged**
