### PR TITLE
permission fix #209

### LINKED ISSUE #197: Do add Keyi Store to Merchants
### Description

Keyi Store is an eCommerce store that accepts all cryptocurrencies. Keyi Store is accepting Nav Coin for their products. Do add Keyi Store.

Website - https://keyi.store

### Motivation

Give more visibility to stores which accept NavCoin.

### Acceptance Criteria

Add merchant to stores listing

- [ ] Title
- [ ] Short Description
- [ ] Link
- [ ] Logo

### PR DESCRIPTION
**Pull request by roast-nav**
Fixes #197, #190, #188, #108, added fr, it.
Set permissions to 664

### Issues Resolved
 #197, #190, #188, #108, #209 

### Preview Links
https://deploy-preview-209--navcoin.netlify.com/en/merchants
https://deploy-preview-209--navcoin.netlify.com/it/merchants
https://deploy-preview-209--navcoin.netlify.com/jp/merchants
https://deploy-preview-209--navcoin.netlify.com/kr/merchants
https://deploy-preview-209--navcoin.netlify.com/ru/merchants
https://deploy-preview-209--navcoin.netlify.com/zh/merchants
https://deploy-preview-209--navcoin.netlify.com/es/buy-navcoin
https://deploy-preview-209--navcoin.netlify.com/fr/buy-navcoin

### CODE REVIEW

**Comment by proletesseract** [comment]
nice work, approving

**Comment by proletesseract** [comment]
@roast-nav can you paste your NAV address for bounty payment?

4 x bounty-low = 400 NAV.

I will make the payment as soon as the funds are available.

**Comment by roast-nav** [comment]
Thanks. Happy to help.

**Comment by roast-nav** [comment]
NNcAFdrDtTdoTFWFQNL341guP3RoLXQ6G6

**Comment by proletesseract** [comment]
@roast-nav paid:

https://www.navexplorer.com/tx/1b06777bda7e7eb3a6224eddf2c27e0698822e8ef7657e4a09666317794276bd

**Pull request merged**
