### PR TITLE
IT translations and Magnum Wallet

### PR DESCRIPTION
**Pull request by roast-nav**
Fresh fork of master branch taken today.

### Checklist.

- [x] Have you assigned/claimed the issues you've resolved in this pull request?
- [ ] Have the issues been moved to the QA column of the NavCoin Websites project? 
- [ ] Have you checked there are no merge conflicts?
- [x] Have you tested the changes work across both mobile and desktop?

### CODE REVIEW

**Comment by roast-nav** [comment]
@proletesseract Please check for a merge. Cheers.

**Comment by proletesseract** [comment]
@roast-nav post your payment address for the bounty-medium.

**Comment by magpie17** [comment]
as requested by "proletesseract" here's my payment address for my contribution to italian website translation - NZB1D88gReSbVWp54JZEqCiQS78unCQTcz

**Comment by roast-nav** [comment]
Cheers @proletesseract NNcAFdrDtTdoTFWFQNL341guP3RoLXQ6G6

**Comment by proletesseract** [comment]
great, i will make the payment today once my cold wallet syncs

**Comment by proletesseract** [comment]
Sorry i spaced on the payment, will do it today!

**Comment by proletesseract** [comment]
im having to re-sync my cold storage wallet sorry. I will get these payments out ASAP

**Comment by proletesseract** [comment]
Paid 350 NAV x 2:

https://www.navexplorer.com/tx/50345d6a8482850e001111e7c09da74c78c1444c2090b35cb6a7aa1386b5c39d

https://www.navexplorer.com/tx/cc31da700942f1cee1e65351527e8b77416cc7fe77040f1905dc3cea103cdc44

**Pull request merged**
