### PR TITLE
🇳🇿 new wallets page 🇳🇿

### PR DESCRIPTION
**Pull request by zanuka**
[Click here to preview](https://deploy-preview-46--navcoin.netlify.com/)

TODO: 

- [x] update svg plaform icons with pngs
- [x] change card colours
- [x] enhance alignments
- [x] enhance responsive grid

### CODE REVIEW

**Comment by craigmacgregor** [comment]
Please correct these:

NavCoin Core should link to -> https://navcoin.org/navcoin-core (not NavHub)

NavPay links to navhub.org/projects/navcoin-core for some reason, should link to -> https://navhub.org/projects/nav-pay/

Subjective feedback:

Not sure about the blue background on the boxes, i thought we were going to largely use the purple on navcoin.org and the blue on navhub to differentiate? Up to you in the end of the day.

Also, i didn't realise the platform icons were download links until i randomly moused over them. Might want to make that call to action clearer somehow.

**Comment by zanuka** [comment]
sounds good @craigmacgregor .... @LauraHarris1 let me know what you think, I can put the purple back in unless you have other colour suggestions

**Comment by LauraHarris1** [comment]
Hey! 

Craig is right about the blue color, can we please change to the purple? Also, can we please move the icons to the same line as the call to action button. 

I feel we need more spacing with the tiles, can we give them some spacing up the top and bottom. I asked Matt
screen shot 2018-08-22 at 1 12 00 pm
 to do this on the other page as well, maybe align with him so that margins are consistent throughout out all pages.

**Comment by craigmacgregor** [comment]
@LauraHarris1 @zanuka i think the icons were split out on their own line because there can be up to 6 or 7 of them per project and there was some concern they wouldn't fit on one line with the Read More button on smaller devices, especially as we now have more tiles horizontally.

**Comment by zanuka** [comment]
@craigmacgregor all updates complete 👊

**Pull request merged**
