### PR TITLE
Added merchants and exchanges

### PR DESCRIPTION
**Pull request by roast-nav**
Tidied up html to both merchants and buy-navcoin, made merchant descriptions a uniform size across 7 languages.

resolves pr#222

Do Not Merge until I Netlify.

### Preview Links

- [y] Have you assigned/claimed the issues you've resolved in this pull request?
- [ ] Have the issues been moved to the QA column of the NavCoin Websites project? 
- [ ] Have you checked there are no merge conflicts?
- [x] Have you tested the changes work across both mobile and desktop?

### CODE REVIEW

**Comment by roast-nav** [comment]
https://deploy-preview-224--navcoin.netlify.com/en/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/es/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/it/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/kr/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/jp/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/ru/buy-navcoin
https://deploy-preview-224--navcoin.netlify.com/zh/buy-navcoin

https://deploy-preview-224--navcoin.netlify.com/en/merchants
https://deploy-preview-224--navcoin.netlify.com/es/merchants
https://deploy-preview-224--navcoin.netlify.com/it/merchants
https://deploy-preview-224--navcoin.netlify.com/kr/merchants
https://deploy-preview-224--navcoin.netlify.com/jp/merchants
https://deploy-preview-224--navcoin.netlify.com/ru/merchants
https://deploy-preview-224--navcoin.netlify.com/zh/merchants

**Comment by roast-nav** [comment]
Google translate was used so there may be some hopefully minor issues. Please let me know of anything that needs to be changed.

**Comment by proletesseract** [comment]
Looks good, does this replace PR #222 ?

**Comment by roast-nav** [comment]
Yes, this pr replaces #222. Next time I'll append to existing pr. My bad.

**Comment by proletesseract** [comment]
Or if you do it this way, then just close the other one. I'll close it now.

**Comment by proletesseract** [comment]
@roast-nav can you paste your NAV address for bounty payment?

2 x bounty-low = 200 NAV for the combined changes to the 2 pages.

**Comment by roast-nav** [comment]
@proletesseract NNcAFdrDtTdoTFWFQNL341guP3RoLXQ6G6

**Comment by proletesseract** [comment]
Paid: https://www.navexplorer.com/tx/2d890b2768af116f6bb703e340788d2152972c626f4c94107065d3c128192bef

**Pull request merged**
