### PR TITLE
buy-navcoin slovak version

### PR DESCRIPTION
**Pull request by glow01**
### Description

Describe in detail what the pull request fixes, adds or removes.

### Issues Resolved

Please tag the issue numbers that this pull request resolves (eg #100, #101).

### Preview Links

Paste the preview links where the changes can be viewed on the netlify deploy preview (you'll need to add these after the PR is made and the preview is deployed).

eg.

https://deploy-preview-205--navcoin.netlify.com/en/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/es/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/it/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/jp/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/kr/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/ru/buy-navcoin

https://deploy-preview-205--navcoin.netlify.com/zh/buy-navcoin

The preview can be found on the pull reqeuest once it's made by clicking `show all checks` > `details`.

### Checklist

- [ ] Have you assigned/claimed the issues you've resolved in this pull request?
- [ ] Have the issues been moved to the QA column of the NavCoin Websites project? 
- [ ] Have you checked there are no merge conflicts?
- [ ] Have you tested the changes work across both mobile and desktop?

### CODE REVIEW

**Comment by glow01** [comment]
There is an updated file of index.sk.md
Ignore the previous one.

**Comment by proletesseract** [comment]
I think there are some more changes required in the configs to enable the slovak translation. Are you just planning to translate this one page, or the whole site?

**Comment by glow01** [comment]
Dear Craig,

I follow this instruction -
https://info.navcoin.org/navcoin-website/how-to-add-a-translation/ - when
translating navcoin webpage. I just uploaded one md file for yo
(buy-navcoin) just to see, if technically is everything translated ok. As
instructed I translated everything in quotation  marks, so* please can you
give me feedback, if this one file is translated and uploaded correctly for
review?*

I am going to translate whole webpage within one month. I contacted you
because I was not sure how to use gitkraken and github to upload everything
ok.

Should I do anything else besides the mentioned instructions to "do more
changes in the configs to enable slovak translation"? Or what else should I
do to have this right?

Best regards,

Rastislav

so 28. 9. 2019 o 3:27 Craig M. <notifications@github.com> napísal(a):

**Comment by glow01** [comment]
@proletesseract I have just uploaded the translations, please could you check whether everything is ok and someone can to start reviewing the texts and merging them into master

**Comment by proletesseract** [comment]
closing because this PR is stale. reopen when you have fixed the merge and build issues.

**Pull request closed without merging**
