### PR TITLE
Resolves issues #96, # 152, #213, #213 thru #219, adding merchants and exchanges.

### LINKED ISSUE #96: Add site to NAVCoin merchant section
http://toys4sex.com.au

It is our pleasure to be able to introduce you to Toys4Sex, Australia’s Online Adult store retailer intended for men and women. Toys4Sex comes with a specially selected range of products that has made its mark within the Australian adult market place.

t4s-newlogo-larger

### PR DESCRIPTION
**Pull request by roast-nav**
### Description

This PR adds merchants and exchanges, adds FR page to exchanges, 

### Issues Resolved

#96, #152, #202, #213 thru #219

### Preview Links

Paste the preview links where the changes can be viewed on the netlify deploy preview (you'll need to add these after the PR is made and the preview is deployed).

DO NOT MERGE - awaiting community response to translations.

The preview can be found on the pull request once it's made by clicking `show all checks` > `details`.

### Checklist

- [y] Have you assigned/claimed the issues you've resolved in this pull request?
- [n] Have the issues been moved to the QA column of the NavCoin Websites project? 
- [n] Have you checked there are no merge conflicts?
- [n] Have you tested the changes work across both mobile and desktop?

### CODE REVIEW

**Comment by roast-nav** [comment]
Also resolves #202

**Comment by proletesseract** [comment]
You'll need to remove the index.fr.md file as its now conflicting with the deleting i just pushed to the master branch.

Can you also try to make the descriptions a bit better and more uniform for the latest merchants?

The descriptions should be 2 lines of text at the maximum width so the boxes line up neatly and describe what the service provides.

Screen Shot 2019-07-09 at 8 58 52 PM

**Comment by roast-nav** [comment]
Will do.

**Comment by proletesseract** [comment]
superseded by #224

**Pull request closed without merging**
