### PR TITLE
adding wikileaks shop

### PR DESCRIPTION
**Pull request by proletesseract**
### Description

Adds wikileaks shop to the merchants section.

### Preview Links

https://deploy-preview-226--navcoin.netlify.com/en/merchants/
https://deploy-preview-226--navcoin.netlify.com/es/merchants/
https://deploy-preview-226--navcoin.netlify.com/it/merchants/
https://deploy-preview-226--navcoin.netlify.com/jp/merchants/
https://deploy-preview-226--navcoin.netlify.com/kr/merchants/
https://deploy-preview-226--navcoin.netlify.com/ru/merchants/
https://deploy-preview-226--navcoin.netlify.com/zh/merchants/

### CODE REVIEW

**Comment by roast-nav** [comment]
Looks good.

**Comment by proletesseract** [comment]
@roast-nav make sure you go to 

`Files Changed` -> `Review Changes` -> `Approve` -> `Submit Review`

I need 1 approved review to merge the changes.

**Comment by proletesseract** [comment]
thanks!

**Comment by roast-nav** [comment]
Renders nicely on both mobile and desktop. :)

**Pull request merged**
